#!/bin/bash

if [[ $EUID -ne 0 ]]
then
  echo "You must be root to run this script."
  exit 1
fi

echo "Welcome to Team Morpheus' CyberPatriot XI Ubuntu 16 Script. This script can only be used by Team Morpheus."
echo "Please Make sure that you have done the following before running this script:"
echo "1) Read the README THOROUGHLY"
echo "2) Read ALL Forensics Questions"
read -p "<Press Enter To Start The Script>"

echo "Please Copy Paste the list of Authorized Users from the ReadME (Hit Ctrl-D when finished)"
while read line
do
    authUsers=("${authUsers[@]}" $line)
done

currentUsers=`awk -F'[/:]' '{if ($3 >= 1000 && $3 != 65534) print $1}' /etc/passwd`
userArr=($currentUsers)

echo "Please copy/paste the list of Authorized Admin from the ReadME Line By Line (Hit Ctrl-D when finished)"

while read line
do
	authAdmins=("${authAdmins[@]}" $line)
done

allAuthUsers=( "${authUsers[@]}" "${authAdmins[@]}" )

unwantedUsers=`echo  ${allAuthUsers[@]} ${currentUsers[@]} | tr ' ' '\n' | sort | uniq -u`

for i in `echo $unwantedUsers`
do
	if [[ "${currentUsers[@]}" in  *"$i"* ]]; then
	while true; do
     	read -p "Would you like to delete user $i? [y/n]" yn
	case $yn in
		[Yy]* ) userdel "$i"; break;;
		[Nn]* ) break;;
		* ) echo "Please answer y or n only.";;
	esac
done
else
	while true; do
	read -p "Would you like to add user $i? [y/n]" yn
	case $yn in 
		[Yy]* ) useradd "$i"; chage -d 0 "$i";;
		[Nn]* ) break;;
		* ) echo "Please answer y or n only.";;
	esac
done
fi
done

for i in "$authAdmins"
do
	usermod -aG sudo $i
done
for i in "$authUsers"
do
	gpasswd -d $i sudo
done

echo "CAUTION: Make sure to not delete the autologin user if you don't have to."
echo "NOTE: All Passwords are changed to Cyb3rPatr!0tPa%%WORD2016"

for i in "$allAuthUsers"
do
	while true; do
		read -p "Would you like to change the password of user $i? [y/n]" yn
		case $yn in
			[Yy]* ) echo "$i:Cyb3rPatr!0tPa%%W0RD2016" | chpasswd;;
			[Nn]* ) break;;
			* ) echo "Please answer y or n only.";;
		esac
	done
done
